config/routes.rb
Rails.application.routes.draw do
  get 'youtube/new', to: 'youtube#new', as: :new_youtube
  get 'youtube/show', to: 'youtube#show', as: :show_youtube
  resources :boards
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/board.rb
class Board < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_action :set_board, only: %i[ show edit update destroy ]

  # GET /boards or /boards.json
  def index
    @boards = Board.all
  end

  # GET /boards/1 or /boards/1.json
  def show
  end

  # GET /boards/new
  def new
    @board = Board.new
  end

  # GET /boards/1/edit
  def edit
  end

  # POST /boards or /boards.json
  def create
    @board = Board.new(board_params)

    respond_to do |format|
      if @board.save
        format.html { redirect_to board_url(@board), notice: "Board was successfully created." }
        format.json { render :show, status: :created, location: @board }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @board.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /boards/1 or /boards/1.json
  def update
    respond_to do |format|
      if @board.update(board_params)
        format.html { redirect_to board_url(@board), notice: "Board was successfully updated." }
        format.json { render :show, status: :ok, location: @board }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @board.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /boards/1 or /boards/1.json
  def destroy
    @board.destroy

    respond_to do |format|
      format.html { redirect_to boards_url, notice: "Board was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_board
      @board = Board.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def board_params
      params.require(:board).permit(:title, :body)
    end
end

app/controllers/youtube_controller.rb
require 'google/apis/youtube_v3'

class YoutubeController < ApplicationController
  def new; end

  def show
    youtube_api_service = Google::Apis::YoutubeV3::YouTubeService.new
    youtube_api_service.key = Rails.application.credentials.YOUTUBE_API_KEY
  
    video_id = extract_video_id(params[:url])
    part = 'snippet,contentDetails,statistics'
  
    begin
      response = youtube_api_service.list_videos(part, id: video_id)
      video = response.items.first
  
      if video
        channel_id = video.snippet.channel_id
        channel_response = youtube_api_service.list_channels('statistics', id: channel_id)
        channel = channel_response.items.first
        
        @video_info = {
          title: video.snippet.title,
          description: video.snippet.description,
          view_count: video.statistics.view_count
        }
        if channel
          @video_info[:channel_subscribers] = channel.statistics.subscriber_count
        else
          flash[:error] = 'Channel not found.'
          redirect_to new_youtube_path and return
        end
      else
      flash[:error] = 'Video not found.'
      redirect_to new_youtube_path and return
    end
    rescue Google::Apis::Error => e
      flash[:error] = e.message
      redirect_to new_youtube_path
    end
  end

  private

  def extract_video_id(url)
    uri = URI.parse(url)
    if uri.host == 'www.youtube.com' && uri.path == '/watch'
      CGI.parse(uri.query)['v'].first
    elsif uri.host == 'youtu.be'
      uri.path[1..]
    else
      nil
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
      # YouTubeの動画リンクからビデオIDを抽出するメソッド
  def extract_youtube_video_id(link)
    # もしリンクが提供されていない場合、ビデオIDは存在しないので nil を返す
    return nil if link.nil?
    
    # URLを解析してビデオIDを取得する
    uri = URI(link)  # リンクのURLをURIオブジェクトに変換
    query = URI.decode_www_form(uri.query)  # URLのクエリパラメータをデコードして取得
    query_hash = Hash[query]  # クエリパラメータをハッシュに変換
    query_hash["v"]  # ハッシュからキー"v"に対応する値、ビデオIDを返す
  end
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/helpers/thumbnail_helper.rb
module ThumbnailHelper
    def youtube_thumbnail(video_id, options = {})
      require 'google/apis/youtube_v3'
      
      options = { show_info: true }.merge(options)
  
      # キャッシュの設定を変更する
      Rails.cache.fetch("youtube_thumbnail_#{video_id}", expires_in: 1.day) do
        service = Google::Apis::YoutubeV3::YouTubeService.new
        service.key = ENV['YOUTUBE_API_KEY']
  
        # ビデオの詳細情報（snippet, statistics）を取得
        video_response = service.list_videos('snippet,statistics', id: video_id)
        video_item = video_response.items.first
  
        if video_item
          thumbnail_url = video_item.snippet.thumbnails.maxres.url
          title = video_item.snippet.title
          view_count = video_item.statistics&.view_count || 'N/A'  # nil の場合に 'N/A' をセット
          upload_date = video_item.snippet.published_at.to_date.strftime('%Y/%m/%d')
  
          content = content_tag(:div, class: 'text-center') do
            image_tag(thumbnail_url, alt: title, **options) +
            if options[:show_info]
              content_tag(:div, class: 'video-info') do
                content_tag(:p, raw("#{title}<br>#{number_with_delimiter(view_count)} views #{upload_date}"))
              end
            end
          end
  
          content
        else
          # ビデオが見つからない場合の処理をここに記述
          content_tag(:div, "Video not found", class: 'text-center')
        end
      end
    end
  end

app/helpers/youtube_helper.rb
module YoutubeHelper
end

app/views/boards/_board.html.erb
<div id="<%= dom_id board %>">
  <p>
    <strong>Title:</strong>
    <%= board.title %>
  </p>

  <p>
    <strong>Body:</strong>
    <%= board.body %>
  </p>

</div>

app/views/boards/_form.html.erb
<%= form_with(model: board) do |form| %>
  <% if board.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(board.errors.count, "error") %> prohibited this board from being saved:</h2>

      <ul>
        <% board.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :body, style: "display: block" %>
    <%= form.text_field :body %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/boards/edit.html.erb
<h1>Editing board</h1>

<%= render "form", board: @board %>

<br>

<div>
  <%= link_to "Show this board", @board %> |
  <%= link_to "Back to boards", boards_path %>
</div>

app/views/boards/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Boards</h1>

<div id="boards">
  <% @boards.each do |board| %>
    <%= render board %>
    <p>
      <%= link_to "Show this board", board %>
    </p>
  <% end %>
</div>

<%= link_to "New board", new_board_path %>

app/views/boards/new.html.erb
<h1>New board</h1>

<%= render "form", board: @board %>

<br>

<div>
  <%= link_to "Back to boards", boards_path %>
</div>

app/views/boards/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @board %>

<!-- YouTubeカラムの始まり -->
<div class="col-md-8 justify-content-center">
  <!-- ここからはYouTube動画のリンクを取得する部分 -->
  <% video_id = extract_youtube_video_id(@post.link) %>
  
  <!-- リンクをクリックすると新しいウィンドウまたはタブで開かれるリンクを作成 -->
  <%= link_to @post.link, target: "_blank" do %>
    <!-- YouTube動画のサムネイルと情報を表示する部分 -->
    <%= youtube_thumbnail(video_id, size: '1280x720', style: 'width: 80%; height: auto;') %>
  <% end %>
  
  <!-- 見出しを表示 -->
  <h1><%= @title %></h1>
</div>
<!-- YouTubeカラムの終わり -->

<div>
  <%= link_to "Edit this board", edit_board_path(@board) %> |
  <%= link_to "Back to boards", boards_path %>

  <%= button_to "Destroy this board", @board, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>YoutubeTest</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/youtube/new.html.erb
<!-- app/views/youtube/new.html.erb -->

<h1>YouTube Video Information</h1>

<%= form_with url: show_youtube_path, method: :get, local: true do |form| %>
  <div class="field">
    <%= form.label :url, "Video URL" %>
    <%= form.text_field :url, required: true %>
  </div>

  <div class="actions">
    <%= form.submit "Get Video Info" %>
  </div>
<% end %>

app/views/youtube/show.html.erb
<!-- app/views/youtube/show.html.erb -->

<h1>Video Information</h1>

<p><strong>Title:</strong> <%= @video_info[:title] %></p>
<p><strong>Description:</strong> <%= @video_info[:description] %></p>
<p><strong>View Count:</strong> <%= @video_info[:view_count] %></p>
<p><strong>Channel Subscribers</strong> <%= @video_info[:channel_subscribers] %></p>